epl/players/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from epl.extensions import db
from epl.models import Club, Player

players_bp = Blueprint('players', __name__, template_folder='templates')

@players_bp.route('/')
def index():
  players = db.session.scalars(db.select(Player)).all()
  return render_template('players/index.html',
                         title='Players Page',
                         players=players)

@players_bp.route('/new', methods=['GET', 'POST'])
def new_player():
  clubs = db.session.scalars(db.select(Club)).all()
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    goals = int(request.form['goals'])
    squad_no = int(request.form['squad_no'])
    img = request.form['img']
    club_id = int(request.form['club_id'])

    clean_sheets = None
    if position == "Goalkeeper":
      val = request.form.get('clean_sheets', '0')
      try:
        clean_sheets = int(val)
      except ValueError:
        clean_sheets = 0  

    player = Player(
        name=name,
        position=position,
        nationality=nationality,
        goals=goals,
        squad_no=squad_no,
        img=img,
        club_id=club_id,
        clean_sheets=clean_sheets
    )
    db.session.add(player)
    db.session.commit()
    flash('add new player successfully', 'success')
    return redirect(url_for('players.index'))
  return render_template('players/new_player.html',
                         title='New Player Page',
                         clubs=clubs)

@players_bp.route('/search', methods=['POST'])
def search_player():
  players = []
  if request.method == 'POST':
    player_name = request.form['player_name']
    players = db.session.scalars(db.select(Player).where(Player.name.like(f'%{player_name}%'))).all()
  return render_template('players/search_player.html',
                         title='Search Player Page',
                         players=players)

@players_bp.route('/<int:id>/info')
def info_player(id):
  player = db.session.get(Player, id)
  return render_template('players/info_player.html',
                         title='Info Player Page',
                         player=player)

@players_bp.route('/<int:id>/update', methods=['GET', 'POST'])
def update_player(id):
  player = db.session.get(Player, id)
  clubs = db.session.scalars(db.select(Club)).all()
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    goals = int(request.form['goals'])
    squad_no = int(request.form['squad_no'])
    img = request.form['img']
    club_id = int(request.form['club_id'])

    clean_sheets = None 
    if position == "Goalkeeper":
      val = request.form.get('clean_sheets', '0')
      try:
        clean_sheets = int(val)
      except ValueError:
        clean_sheets = 0

    player.name = name
    player.position = position
    player.nationality = nationality
    player.goals = goals
    player.squad_no = squad_no
    player.img = img
    player.club_id = club_id
    player.clean_sheets = clean_sheets

    
    db.session.commit()
    flash('update player successfully', 'success')
    return redirect(url_for('players.index'))

  return render_template('players/update_player.html',
                         title='Update Player Page',
                         player=player,
                         clubs=clubs)

epl/players/templates/players/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row">
      <div class="col">
        <a href="{{url_for('players.new_player')}}" class="btn btn-outline-success">
          <i class="bi bi-folder-plus"></i>
          Add New Player
        </a>
      </div>
      <div class="col">
        <form method="post"
        hx-target="#result"
        hx-trigger="submit"
        hx-post="{{url_for('players.search_player')}}"
        hx-on::after-request="if(event.detail.successful) this.reset()">
          <div class="input-group mb-3">
            <input name="player_name" type="text" class="form-control" placeholder="Search by Player's name">
            <button class="btn btn-outline-secondary" type="submit">
              <i class="bi bi-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
    <table class="table table-hover mt-3">
      <thead>
        <th>#</th>
        <th>Player Name</th>
        <th>Action</th>
      </thead>
      <tbody id="result">
        {% for player in players %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{player.name}}</td>
            <td>
              <a href="{{url_for('players.info_player', id=player.id)}}" class="btn btn-outline-info btn-sm">
                <i class="bi bi-info-circle"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
{% endblock %}

epl/players/templates/players/info_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row mb-3">
      <div class="col-md-4 mt-3">
        <div class="card">
          <img src="{{player.img}}" alt="" class="img-thumbnail p-5">
          <div>
            <h4 class="text-center text-success">
              Player Photo
            </h4>
          </div>
        </div>
      </div>
      <div class="col-md-8 mt-3">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col"><h2>Player Name</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.name}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Position</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.position}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Nationality</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.nationality}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Goals</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.goals}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Squad Number</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.squad_no}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Clean Sheets</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.clean_sheets|default('N/A')}}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Club</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{player.club.name}}</h2></div>
            </div>
            <hr>
            
            <div class="row mt-5">
              <div class="col">
                <a href="{{url_for('players.index')}}" class="btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Back to Player Page
                </a>
              </div>
              <div class="col">
                <a href="{{url_for('players.update_player', id=player.id)}}" class="float-end btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Edit Player
                </a>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    
  </div>
{% endblock %}

epl/players/templates/players/new_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-3">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Player Name</label>
        <input name="name" type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Position</label>
        <select name="position" class="form-select">
          <option value="Goalkeeper">Goalkeeper</option>
          <option value="Defender">Defender</option>
          <option value="Midfielder">Midfielder</option>
          <option value="Forward">Forward</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="nationality" class="form-label">Nationality</label>
        <input name="nationality" type="text" class="form-control" id="nationality" required>
      </div>
      <div class="mb-3">
        <label for="goals" class="form-label">Goals</label>
        <input name="goals" type="number" class="form-control" id="goals" required>
      </div>
      <div class="mb-3">
        <label for="squad_no" class="form-label">Squad Number</label>
        <input name="squad_no" type="number" class="form-control" id="squad_no" required>
      </div>
      
      <div class="mb-3">
        <label for="clean_sheets" class="form-label">Clean Sheets <small class="text-muted"></small></label>
        <input type="number" name="clean_sheets" class="form-control" value="" min="0">
      </div>
      
      <div class="mb-3">
        <label for="img" class="form-label">Image URL</label>
        <input name="img" type="text" class="form-control" id="img" required>
      </div>
      <div class="mb-3">
        <label for="club_id" class="form-label">Select Club</label>
        <select name="club_id" class="form-select">
          {% for club in clubs %}
            <option value="{{club.id}}">{{club.name}}</option>
          {% endfor %}

        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">

        New Player
      </button>
    </form>
  </div>
{% endblock %}

epl/players/templates/players/search_player.html
{% for player in players %}
  <tr>
    <td>{{loop.index}}</td>
    <td>{{player.name}}</td>
    <td>
      <a href="{{url_for('players.info_player', id=player.id)}}" class="btn btn-outline-info btn-sm">
        <i class="bi bi-info-circle"></i>
      </a>
    </td>
  </tr>
{% endfor %}

epl/players/templates/players/update_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Player Name</label>
        <input value="{{player.name}}" name="name" readonly type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Position</label>
        <select name="position" class="form-select">
          <option value="Goalkeeper" {% if player.position == 'Goalkeeper' %}selected{% endif %}>Goalkeeper</option>
          <option value="Defender" {% if player.position == 'Defender' %}selected{% endif %}>Defender</option>
          <option value="Midfielder" {% if player.position == 'Midfielder' %}selected{% endif %}>Midfielder</option>
          <option value="Forward" {% if player.position == 'Forward' %}selected{% endif %}>Forward</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="nationality" class="form-label">Nationality</label>
        <input value="{{player.nationality}}" name="nationality" type="text" class="form-control" id="nationality" required>
      </div>
      <div class="mb-3">
        <label for="goals" class="form-label">Goals</label>
        <input value="{{player.goals}}" name="goals" type="number" class="form-control" id="goals" required>
      </div>
      <div class="mb-3">
        <label for="squad_no" class="form-label">Squad No</label>
        <input value="{{player.squad_no}}" name="squad_no" type="number" class="form-control" id="squad_no" required>
      </div>
      
      <div class="mb-3">
        <label for="clean_sheets" class="form-label">Clean Sheets <small class="text-muted"></small></label>
        <input value="{{player.clean_sheets|default('')}}" name="clean_sheets" type="number" class="form-control" id="clean_sheets" min="0">
      </div>
      
      <div class="mb-3">
        <label for="img" class="form-label">Image URL</label>
        <input value="{{player.img}}" name="img" type="text" class="form-control" id="img" required>
      </div>
      <div class="mb-3">
        <label for="club_id" class="form-label">Select Club</label>
        <select name="club_id" class="form-select">
          {% for club in clubs %}
            <option value="{{club.id}}" {% if player.club.name == club.name %}selected{% endif %}>{{club.name}}</option>
          {% endfor %}

        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-pencil-square"></i>
        Update Player
      </button>
    </form>
  </div>
{% endblock %}